[versions]

java = "17"

androidGradle = "9.2.0" # https://developer.android.com/reference/tools/gradle-api
kompress = "1.4.3"
kotlin = "2.3.21" # https://github.com/JetBrains/kotlin/releases
kotlinxIo = "0.9.0" # https://github.com/Kotlin/kotlinx-io/releases
kotlinBrowser = "2026.4.15" # https://github.com/JetBrains/kotlin-wrappers/releases
dokka = "2.2.0" # https://github.com/Kotlin/dokka/releases
karmaConventions = "1.16.1" # https://github.com/karmakrafts/karma-conventions/tags
gradleNexus = "2.0.0" # https://github.com/gradle-nexus/publish-plugin/releases
fflate = "0.8.2" # https://github.com/101arrowz/fflate/releases # TODO: this is a deprecated impl detail, get rid of it

[libraries]

kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlin-wrappers-browser = { module = "org.jetbrains.kotlin-wrappers:kotlin-browser", version.ref = "kotlinBrowser" }
kotlinx-io-bytestring = { module = "org.jetbrains.kotlinx:kotlinx-io-bytestring", version.ref = "kotlinxIo" }
kotlinx-io-core = { module = "org.jetbrains.kotlinx:kotlinx-io-core", version.ref = "kotlinxIo" }

[plugins]

android-library = { id = "com.android.kotlin.multiplatform.library", version.ref = "androidGradle" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
karmaConventions = { id = "dev.karmakrafts.conventions.karma-conventions", version.ref = "karmaConventions" }
gradleNexus = { id = "io.github.gradle-nexus.publish-plugin", version.ref = "gradleNexus" }